version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  allow:
  - dependency-type: direct
  - dependency-type: indirect
  ignore:
  - dependency-name: redox_syscall
    versions:
    - 0.2.7
  - dependency-name: openssl-sys
    versions:
    - 0.9.62
  - dependency-name: openssl
    versions:
    - 0.10.34
  - dependency-name: syn
    versions:
    - 1.0.71
  - dependency-name: webview2
    versions:
    - 0.1.0
  - dependency-name: webview2-sys
    versions:
    - 0.1.0
  - dependency-name: tauri-utils
    versions:
    - 1.0.0-beta-rc.1
  - dependency-name: tauri
    versions:
    - 1.0.0-beta-rc.4
  - dependency-name: tauri-macros
    versions:
    - 1.0.0-beta-rc.1
- package-ecosystem: npm
  directory: "/gui"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: framer-motion
    versions:
    - 3.10.0
    - 3.4.0
    - 3.4.1
    - 3.4.2
    - 3.6.0
    - 3.6.1
    - 3.6.2
    - 3.6.3
    - 3.6.4
    - 3.6.5
    - 3.8.1
    - 3.8.2
    - 3.9.0
    - 3.9.1
    - 3.9.2
    - 3.9.3
    - 4.0.0
    - 4.0.1
    - 4.1.10
    - 4.1.6
    - 4.1.7
    - 4.1.8
  - dependency-name: "@types/react"
    versions:
    - 17.0.3
    - 17.0.4
  - dependency-name: vite
    versions:
    - 2.2.3
  - dependency-name: "@tauri-apps/cli"
    versions:
    - 1.0.0-beta-rc.2
    - 1.0.0-beta-rc.3
    - 1.0.0-beta-rc.4
  - dependency-name: "@tauri-apps/api"
    versions:
    - 1.0.0-beta-rc.3
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.1
    - 12.7.2
    - 12.7.3
    - 12.7.4
    - 12.8.1
    - 13.0.12
    - 13.0.9
    - 13.1.1
    - 13.1.5
  - dependency-name: "@testing-library/jest-dom"
    versions:
    - 5.12.0
  - dependency-name: "@chakra-ui/icons"
    versions:
    - 1.0.5
    - 1.0.6
    - 1.0.7
    - 1.0.8
  - dependency-name: "@chakra-ui/react"
    versions:
    - 1.3.2
    - 1.3.4
    - 1.4.0
    - 1.4.2
  - dependency-name: "@types/node"
    versions:
    - 14.14.32
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.5
