# cargo-features = ["resolver"]

[workspace]
members = [
  "core",
  "cli",
  "league",
  "storage",
  "gui/src-tauri",
]
# resolver = "2"

[profile.release]
lto = true 
opt-level = "s" #"z"
panic = "abort"
