# cargo-features = ["resolver"]

[workspace]
members = [
  "core",
  "cli",
  "gui-druid",
  "gui-orbtk",
  "gui",
  "league",
  "storage",
]
# resolver = "2"

[profile.release]
lto = true
panic = 'abort'
