[package]
name = "wtools"
version = "0.1.0"
authors = ["FabianLars"]
build = "build.rs"
edition = "2018"

[features]
default = ["gui"]

gui = ["iced"]
riot-api = []
league = []

[target.'cfg(windows)'.build-dependencies]
winres = "0.1"

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "time"] }
reqwest = { version = "0.10", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
clap = { git = "https://github.com/clap-rs/clap/" }
chrono = "0.4"
futures = "0.3"
iced = { git = "https://github.com/hecrj/iced.git", branch = "master", features = ["tokio"], optional = true }
directories ="2.0"
nfd = { git = "https://github.com/EmbarkStudios/nfd-rs.git", branch = "update-submodule" }