[package]
name = "wtools"
version = "0.1.0"
authors = ["FabianLars"]
edition = "2018"

[dependencies]
reqwest = { version = "0.10", features = ["blocking", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
chrono = "0.4"