[package]
name = "wtools"
version = "0.1.0"
authors = ["FabianLars"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "time"] }
reqwest = { version = "0.10", features = ["json", "cookies"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
structopt = "0.3"
chrono = "0.4"
futures = "0.3"
iced = { git = "https://github.com/Finnerale/iced.git", branch = "feature/text-selection", features = ["tokio"] }
directories = "2.0"