<?php
return [
    "Datei:Akali True Damage-Akali (Freestyle) M.png",
    "Datei:Akali True Damage-Akali (Katzenauge) M.png",
    "Datei:Akali True Damage-Akali (Perlmutt) M.png",
    "Datei:Akali True Damage-Akali (Rosenquarz) M.png",
    "Datei:Akali True Damage-Akali (Rubin) M.png",
    "Datei:Akali True Damage-Akali (Saphir) M.png",
    "Datei:Akali True Damage-Akali (Smaragd) M.png",
    "Datei:Akali True Damage-Akali L.jpg",
    "Datei:Akali True Damage-Akali M.png",
    "Datei:Akali True Damage-Akali S.jpg",
    "Datei:Akali True Damage-AkaliCircle.png",
    "Datei:Ekko True Damage-Ekko (Amethyst) M.png",
    "Datei:Ekko True Damage-Ekko (Freestyle) M.png",
    "Datei:Ekko True Damage-Ekko (Katzenauge) M.png",
    "Datei:Ekko True Damage-Ekko (Perlmutt) M.png",
    "Datei:Ekko True Damage-Ekko (Rosenquarz) M.png",
    "Datei:Ekko True Damage-Ekko (Rubin) M.png",
    "Datei:Ekko True Damage-Ekko (Türkis) M.png",
    "Datei:Ekko True Damage-Ekko L.jpg",
    "Datei:Ekko True Damage-Ekko M.png",
    "Datei:Ekko True Damage-Ekko S.jpg",
    "Datei:Ekko True Damage-EkkoCircle.png",
    "Datei:Qiyana True Damage-Qiyana (Prestige-Edition) L.jpg",
    "Datei:Qiyana True Damage-Qiyana (Prestige-Edition) S.jpg",
    "Datei:Qiyana True Damage-Qiyana (Prestige-Edition)Circle.png",
    "Datei:Qiyana True Damage-Qiyana L.jpg",
    "Datei:Qiyana True Damage-Qiyana S.jpg",
    "Datei:Qiyana True Damage-QiyanaCircle.png",
    "Datei:Senna True Damage- Model 01.png",
    "Datei:Senna True Damage- Splash Konzept 01.jpg",
    "Datei:Senna True Damage- Splash Konzept 02.jpg",
    "Datei:Senna True Damage- Splash Konzept 03.gif",
    "Datei:Senna True Damage-Senna (Amethyst) M.png",
    "Datei:Senna True Damage-Senna (Freestyle) M.png",
    "Datei:Senna True Damage-Senna (Katzenauge) M.png",
    "Datei:Senna True Damage-Senna (Perlmutt) M.png",
    "Datei:Senna True Damage-Senna (Rubin) M.png",
    "Datei:Senna True Damage-Senna (Saphir) M.png",
    "Datei:Senna True Damage-Senna (Zitrin) M.png",
    "Datei:Senna True Damage-Senna L.jpg",
    "Datei:Senna True Damage-Senna M.png",
    "Datei:Senna True Damage-Senna S HD.jpg",
    "Datei:Senna True Damage-Senna S.jpg",
    "Datei:Senna True Damage-SennaCircle.png",
    "Datei:Yasuo True Damage-Yasuo (Amethyst) M.png",
    "Datei:Yasuo True Damage-Yasuo (Aquamarin) M.png",
    "Datei:Yasuo True Damage-Yasuo (Freestyle) M.png",
    "Datei:Yasuo True Damage-Yasuo (Katzenauge) M.png",
    "Datei:Yasuo True Damage-Yasuo (Obsidian) M.png",
    "Datei:Yasuo True Damage-Yasuo (Perlmutt) M.png",
    "Datei:Yasuo True Damage-Yasuo (Rubin) M.png",
    "Datei:Yasuo True Damage-Yasuo L.jpg",
    "Datei:Yasuo True Damage-Yasuo M.png",
    "Datei:Yasuo True Damage-Yasuo S.jpg",
    "Datei:Yasuo True Damage-YasuoCircle.png",
];