[package]
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"
name = "gui"
publish = false
version = "0.1.0"

[dependencies]
pretty_env_logger = "0.4"
vgtk = {git = "https://github.com/bodil/vgtk"}
