[package]
name = "cli"
version = "0.1.0"
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"
publish = false
default-run = "cli"

[features]
server = ["riot-api", "league-wiki"]

riot-api = ["league/riot-api"]
league-wiki = ["league"]
skylords-wiki = ["skylords"]

[dependencies]
wtools = { path = "../core" }
league = { path = "../league", optional = true }
skylords = { path = "../skylords", optional = true }

tokio = { version = "0.2", features = ["macros"] }
clap = { git = "https://github.com/clap-rs/clap/" }
serde_json = { version = "1.0", features = ["preserve_order"] }