[package]
name = "wtools"
version = "0.1.0"
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "time"] }
base64 = "0.12"
serde_json = { version = "1.0", features = ["preserve_order"] }
reqwest = { version = "0.10", features = ["json", "cookies"] }
ring = "0.16"
directories = { version = "3" }
anyhow = "1.0"