[package]
name = "core"
version = "0.1.0"
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"

[features]
riot-api = []
league = ["base64"]
skylords = []

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "time"] }
futures = "0.3"
base64 = { version = "0.12", optional = true }
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
reqwest = { version = "0.10", features = ["json", "cookies"] }