[package]
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"
name = "wtools"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
async-std = "1"
surf = { git = "https://github.com/http-rs/surf", branch = "main" }
serde_json = { version = "1.0", features = ["preserve_order"] }