[package]
name = "core"
version = "0.1.0"
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"

[features]
riot-api = []
league = ["chrono", "futures"]
skylords = []

[dependencies]
tokio = { version = "0.2", features = ["macros", "fs", "time"] }
futures = { version = "0.3", optional = true }
base64 = "0.12"
chrono = { version = "0.4", optional = true }
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
reqwest = { version = "0.10", features = ["json", "cookies"] }
ring = "0.16"
directories = { version = "2" }
anyhow = "1.0"