[package]
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"
name = "wtools"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
directories = "3"
reqwest = { version = "0.10", features = ["json", "cookies"] }
rand = "0.7"
rand_chacha = "0.2"
chacha20poly1305 = "0.5"
bincode = "1"
serde_json = { version = "1.0", features = ["preserve_order"] }
tokio = { version = "0.2", features = ["macros", "fs", "time"] }