[package]
authors = ["FabianLars <fabianlars@fabianlars.de>"]
edition = "2018"
name = "wtools"
version = "0.1.0"

[dependencies]
anyhow = "1.0"
reqwest = { version = "0.10", features = ["json", "cookies"] }
serde_json = { version = "1.0", features = ["preserve_order"] }
tokio = { version = "0.2", features = ["fs"] }