[build]
distDir = "../dist"
devPath = "http://localhost:5173"
beforeDevCommand = "pnpm start"
beforeBuildCommand = "pnpm build"

[tauri.bundle]
active = true
targets = "all"
identifier = "de.FabianLars.mw-toolbox"
icon = ["icons/32x32.png", "icons/128x128.png", "icons/128x128@2x.png", "icons/icon.icns", "icons/icon.ico"]
copyright = "MIT"
category = "DeveloperTool"
shortDescription = "mw-toolbox GUI"
longDescription = "mw-toolbox GUI"

[tauri.allowlist]
all = false

[tauri.allowlist.dialog]
all = false
open = true

[tauri.allowlist.shell]
all = false
open = "^https://docs.rs/regex/$"

[[tauri.windows]]
title = "mw-toolbox by FabianLars"
width = 1280
height = 720
minWidth = 500
minHeight = 480
resizable = true

[tauri.security]
csp = "default-src 'self'"
freezePrototype = true

[tauri.updater]
active = true
dialog = true
pubkey = "dW50cnVzdGVkIGNvbW1lbnQ6IG1pbmlzaWduIHB1YmxpYyBrZXk6IDVCRjExMDk5REExQTlBNjgKUldSb21ocmFtUkR4V3lyaW1kQmQvYklqeGkyd2R1TmExQ1MzQVVJanpEZ3A4WjY3M0xsc3BFZU4K"
endpoints = ["https://api.fabianlars.de/v1/update/mw-toolbox/{{target}}/{{arch}}/{{current_version}}"]
