name: Format

on:
    workflow_dispatch:
    pull_request:
    push:
        branches:
            - main

jobs:
    rust:
        runs-on: ubuntu-latest
        steps:
            - uses: hecrj/setup-rust-action@v1
              with:
                  components: rustfmt

            - uses: actions/checkout@v2

            - name: Check format
              run: cargo fmt --all -- --check

    js:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: gui
        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install yarn
              run: npm i -g yarn

            - uses: actions/cache@v2
              with:
                  path: node_modules
                  key: js-test-cache-${{ hashFiles('yarn.lock') }}

            - name: Install dependencies
              run: yarn install

            - name: Check Prettier compliance
              run: yarn lint