name: Publish app

on:
  create:
  workflow_dispatch:

env:
  WTOOLS_AEAD_KEY: ${{ secrets.WTOOLS_AEAD_KEY }}
  TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
  CN_APPLICATION: "fabianlars/mw-toolbox"

jobs:
  draft:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - name: create draft release
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release draft ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  build_desktop:
    if: ${{ startsWith(github.ref, 'refs/tags/v') }}

    strategy:
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v7

      - uses: dtolnay/rust-toolchain@stable

      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: "lts/*"

      - name: Install dependencies (ubuntu only)
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev librsvg2-dev

      - name: Install pnpm and project dependencies
        uses: pnpm/action-setup@v6
        with:
          version: 10
          run_install: |
            - cwd: gui

      - name: Build app
        run: |
          cd gui
          pnpm tauri build

      - name: upload assets
        uses: crabnebula-dev/cloud-release@v0
        with:
          command: release upload ${{ env.CN_APPLICATION }} --framework tauri
          api-key: ${{ secrets.CN_API_KEY }}

  # publish:
  #   needs: [build_desktop]

  #   runs-on: ubuntu-latest

  #   steps:
  #     - uses: actions/checkout@v7

  #     - name: publish release
  #       uses: crabnebula-dev/cloud-release@v0
  #       with:
  #         command: release publish ${{ env.CN_APPLICATION }} --framework tauri
  #         api-key: ${{ secrets.CN_API_KEY }}