name: Test

on:
    pull_request:
    push:
        branches:
            - main

jobs:
    rust:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: hecrj/setup-rust-action@v1
              with:
                  components: clippy
                  rust-version: nightly

            - uses: actions/cache@v2
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      target
                  key: test-cache-${{ hashFiles('**/Cargo.lock') }}

            - name: Run clippy
              run: cargo clippy --all-features

            - name: Run tests
              run: cargo test --verbose --all --all-features

    js:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: gui

        steps:
            - uses: actions/checkout@v2

            - name: Setup Node
              uses: actions/setup-node@v1
              with:
                  node-version: '14'

            - name: Install yarn
              run: npm i -g yarn

            - name: Install dependencies
              run: yarn

            - name: Run tests
              run: yarn test
